name: Nix Flake

on:
  push:
    branches: [main]
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'src/**'
      - 'build.zig'
      - '.github/workflows/nix.yml'
  pull_request:
    branches: [main]
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - 'src/**'
      - 'build.zig'
      - '.github/workflows/nix.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - name: Check flake
        run: nix flake check

      - name: Build wx
        run: nix build

      - name: Test wx binary
        run: |
          ./result/bin/wx --help
          ./result/bin/wx --version || true

      - name: Enter dev shell
        run: |
          nix develop --command zig version
